---
logging.level.org.springframework.boot.autoconfigure: ERROR
logging.level.org.cedar.onestop.elastic.common: DEBUG
logging.level.org.cedar.onestop.api.search: DEBUG

elasticsearch:
  ssl:
    enabled: false