---

##spring.security.oauth2.client.client-id: "urn:gov:gsa:openidconnect.profiles:sp:sso:noaa:onestop_user_8080"
#security.oauth2.client.client-secret: bael-secret

## Single key URI:
#spring.security.oauth2.resource.jwt.key-uri: https://idp.int.identitysandbox.gov/api/openid_connect/certs

## Introspection endpoint:
#3spring.security.oauth2.resource.token-info-uri: https://idp.int.identitysandbox.gov/api/openid_connect/userinfo

#spring.security.oauth2.resource.jwt.jwk-set-uri: https://idp.int.identitysandbox.gov/api/openid_connect/certs

#spring.security.oauth2.resource.jwt.issuer-uri: https://idp.int.identitysandbox.gov/
#spring.security.oauth2.resourceserver.opaquetoken.introspection-uri: https://idp.int.identitysandbox.gov/api/openid_connect/certs
#spring.security.oauth2.resourceserver.opaquetoken.client-id: "urn:gov:gsa:openidconnect.profiles:sp:sso:noaa:onestop_user_8080"
#spring.security.oauth2.resourceserver.opaquetoken.client-secret: ""
#spring.security.oauth2.resource.token-info-uri: https://idp.int.identitysandbox.gov/api/openid_connect/userinfo

#spring.security.oauth2.resourceserver.user-name-attribute: sub

# Use the token info, can be set to false to use the user info.
#spring.security.oauth2.resourceserver.prefer-token-info: false

#spring.security.oauth2.resource.service-id: resource

# URI of the token decoding endpoint.
#spring.security.oauth2.resource.token-info-uri:

# The token type to send when using the userInfoUri.
#spring.security.oauth2.resource.token-type:

# URI of the user endpoint.
#spring.security.oauth2.resourceserver.user-info-uri: https://idp.int.identitysandbox.gov/api/openid_connect/userinfo

