// force webpack to include the fonts in the build/dist
import './fonts/Merriweather-Regular.ttf'
import './fonts/Merriweather-Bold.ttf'
import './fonts/Merriweather-Italic.ttf'
import './fonts/Merriweather-BoldIt.ttf'
import './fonts/Merriweather-Light.ttf'
import './fonts/Merriweather-LightIt.ttf'
import './fonts/SourceSansPro-Regular.ttf'
import './fonts/SourceSansPro-Italic.ttf'
import './fonts/SourceSansPro-Bold.ttf'
import './fonts/SourceSansPro-BoldItalic.ttf'
import './fonts/SourceSansPro-Light.ttf'
import './fonts/SourceSansPro-LightItalic.ttf'
import './fonts/SourceSansPro-SemiBold.ttf'
import './fonts/SourceSansPro-SemiBoldItalic.ttf'
