apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: cedardevs/onestop-api-metadata
    context: ./api-metadata
    docker:
      buildArgs:
        DATE: now
        VCS_REF: local
        VERSION: 2.3.0
        WAR_NAME: onestop-metadata.war
  - image: cedardevs/onestop-api-search
    context: ./api-search
    docker:
      buildArgs:
        DATE: now
        VCS_REF: local
        VERSION: 2.3.0
        WAR_NAME: onestop-search.war
  - image: cedardevs/onestop-client
    context: ./client
    docker:
      buildArgs:
        DATE: now
        VCS_REF: local
        VERSION: 2.3.0
        TAR_NAME: onestop-client.tar.gz

deploy:
  helm:
    releases:
    ###############################################################################
    # API ADMIN
    ###############################################################################
    - name: api-admin
      chartPath: helm/api-admin
      values:
        # skaffold may not build/deploy w/the latest if this is not set here
        image: cedardevs/onestop-api-metadata
      imageStrategy:
        helm: {}
      setValues:
        # allows api-admin to be exposed outside the cluster in dev
        # features are directly tied to `export SPRING_PROFILES_ACTIVE='feat1,feat2,...'
        # all features default to "false" in base chart, unless otherwise overridden
        features.icam: false
        features.manual-upload: false
        features.kafka-ingest: false
        features.sitemap: true
        # env.ELASTICSEARCH_HOST: onestop-dev-elasticsearch
        config: |-
          ---
          logging.level.org.cedar.onestop.api.metadata: DEBUG
          ---
          spring:
            profiles: sitemap
          etl:
            sitemap:
              delay:
                initial: 60000
    ###############################################################################
    # API SEARCH
    ###############################################################################
    - name: api-search
      chartPath: helm/api-search
      values:
        # skaffold may not build/deploy w/the latest if this is not set here
        image: cedardevs/onestop-api-search
      imageStrategy:
        helm: {}
      setValues:
        service.type: NodePort
        service.nodePort: 30097
        # allows api-search to be exposed outside the cluster in dev
        # features are directly tied to `export SPRING_PROFILES_ACTIVE='feat1,feat2,...'
        # all features default to "false" in base chart, unless otherwise overridden
        features.login-gov: false
        features.sitemap: true
        # env.ELASTICSEARCH_HOST: onestop-dev-elasticsearch
        env.SITEMAP_CLIENT_PATH: https://sciapps.colorado.edu/onestop
        env.SITEMAP_API_PATH: https://sciapps.colorado.edu/onestop-search
        # config: |-
        #   ---
        #   logging.level.org.cedar.onestop.api.search: DEBUG
    ###############################################################################
    # CLIENT
    ###############################################################################
    - name: client
      chartPath: helm/client
      values:
        # skaffold may not build/deploy w/the latest if this is not set here
        image: cedardevs/onestop-client
      imageStrategy:
        helm: {}
      setValues:
        # allows api-search to be exposed outside the cluster in dev
        prefixPath: onestop
        apiSearch.endpoint: api-search:8080/onestop-search

    ###############################################################################
    # ELASTICSEARCH
    ###############################################################################
    - name: elasticsearch
      chartPath: helm/elasticsearch
      setValues:
        service.type: NodePort
        service.nodePort: 30092

    ###############################################################################
    # DEV DEPENDENCIES
    ###############################################################################
    - name: onestop-dev
      chartPath: helm/onestop-dev
