apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    tier: "frontend"
    devmode: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      restartPolicy: Always
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:5.5.3
        env:
        - name: CLUSTER_NAME
          value: elasticsearch # default; should be variable value in prod version
#        - name: SERVER_BASEPATH
#          value: /api/v1/namespaces/default/services/kibana:http:proxy
        ports:
        - containerPort: 5601
          name: http
