apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    environment: dev
    tier: "frontend"
    devmode: "true"
spec:
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
      nodePort: 32001
  type: NodePort
