# Default values for onestop-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cedardevs/onestop-stream-manager
  tag: master-SNAPSHOT
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  type: ClusterIP
  port: 80

autoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: ## Required when enabled
  cpu:
    ## At least one of the following metrics to scale on is required when enabled
    ## If both are provided, both will be used to trigger scaling
    averageValue:
    averageUtilization: ## Note: utilization is based on resources.requests.cpu and resources.limits.cpu

config: # inline application config yaml

kafka: {}
#  override just the name of kafka's headless service:
#  serviceNameOverride:
#  override the full bootstrap servers string:
#  bootstrapServers:

cp-schema-registry: {}
#  override just the name of schema registry's service:
#  serviceNameOverride:
#  override the full url of the schema registry:
#  url:

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
