package main

const searchCollectionCmd = "searchcollection"
const searchGranuleCmd = "searchgranule"
const searchFlattenedGranuleCmd = "searchflattenedgranule"

const textQueryFlag = "query"
const textQueryShortFlag = "q"
const dateFilterFlag = "date"
const dateFilterShortFlag = "d"
const spatialFilterFlag = "area"
const spatialFilterShortFlag = "g" //as in geometry
const maxFlag = "max"
const maxShortFlag = "l"
const offsetFlag = "offset"
const offsetShortFlag = "p" //as in page
const startTimeFlag = "start-time"
const startTimeShortFlag = "s"
const startTimeScdrFlag = "stime"
const endTimeFlag = "end-time"
const endTimeShortFlag = "e"
const endTimeScdrFlag = "etime"
const availableFlag = "available"
const availableShortFlag = "a"
const metadataFlag = "metadata"
const metadataShortFlag = "m"
const typeFlag = "type"
const typeShortFlag = "t"

const queryDescription = "Search flattened granules with text query"
const dateDescription = "DATE must be a string describing a date. Format YYYY/MM/DD. Current year is assumed if the year part in DATE is ommited, e.g. 01-30. Any time information in DATE is disregarded. Files with data between DATE midnight and next day midnight are selected."
const areaDescription = "Locate files which intersect with the specified polygon AREA. The polygon must be a regular one (closed, no self-intersection, no hole) with coordinates (longitude, latitude) separated by \",\" like POLYGON((30.31 60.2, 31.21 60.2, 31.21 60.76, 30.31 60.76, 30.31 60.2)) "
const maxDescription = "Maximum number of results returned."
const offsetDescription = "Page number starting at 0"
const startTimeDescription = "Match files occurring on or after this date. Format YYYY/MM/DD."
const startTimeScdrDescription = "Same behavior as start-time, but short hand flag for scdr files. Format YYYY/MM/DD."
const endTimeScdrDescription = "Same behavior as end-time, but short hand flag for scdr files. Format YYYY/MM/DD."
const endTimeDescription = "Match files occurring on or before this date. Format YYYY/MM/DD."
const availableDescription = "Searches OneStop for files associated with [COLLECTION]"
const metadataDescription = "Text search against available metadata."
