{{- if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onestop-user.configname" . }}
  labels:
    {{- include "onestop-user.labels" . | nindent 4 }}
data:
  application.yml: {{ .Values.config | toYaml | indent 4 }}
{{- end }}