---
# assumes you've installed the ECK CRDs in your cluster
# [infraInstall.sh]
# https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html

# upgrading from previous versions:
# https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-upgrading-eck.html

# if you need to uninstall ECK:
# [infraUninstall.sh]
# https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-uninstalling-eck.html

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "onestop-dev.fullname" . }}
spec:
  version: 7.17.5
  nodeSets:
    - name: default
      count: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
        repositories.url.allowed_urls: ["https://*.s3.amazonaws.com/*"]
      podTemplate:
        spec:
          initContainers:
          - name: install-plugins
            command:
            - sh
            - -c
            - |
              bin/elasticsearch-plugin install --batch repository-s3
{{/*        thread_pool.snapshot.max: 8*/}}

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "onestop-dev.fullname" . }}
spec:
  version: 7.17.5
  count: 1
  elasticsearchRef:
    name: {{ include "onestop-dev.fullname" . }}
  http:
    service:
      spec:
        type: LoadBalancer # expose outside cluster on `https://localhost:5601

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onestop-dev.fullname" . }}-es-elastic-user # override the default secret used by ECK operator
type: Opaque
data:
  elastic: Zm9hbWNhdA== # development user:pass => elastic:foamcat

---
#apiVersion: apm.k8s.elastic.co/v1beta1
#kind: ApmServer
#metadata:
#  name: onestop
#spec:
#  version: 7.5.2
#  count: 1
#  elasticsearchRef:
#    name: onestop
