# Modified from: https://github.com/elastic/beats/blob/master/deploy/kubernetes/filebeat-kubernetes.yaml
{{ if .Values.filebeat.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onestop-dev.fullname" . }}-filebeat
  labels:
    {{- include "onestop-dev.labels.filebeat" . | nindent 4 }}
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    # To enable hints based autodiscover, remove `filebeat.inputs` configuration and uncomment this:
    #filebeat.autodiscover:
    #  providers:
    #    - type: kubernetes
    #      node: ${NODE_NAME}
    #      hints.enabled: true
    #      hints.default_config:
    #        type: container
    #        paths:
    #          - /var/log/containers/*${data.kubernetes.container.id}.log

    processors:
      - add_cloud_metadata:
      - add_host_metadata:

    output.elasticsearch:
      hosts: ['https://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      ssl.certificate_authorities:
      - /mnt/elastic/tls.crt
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "onestop-dev.fullname" . }}-filebeat
  labels:
    {{- include "onestop-dev.labels.filebeat" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "onestop-dev.selectorLabels.filebeat" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "onestop-dev.selectorLabels.filebeat" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "onestop-dev.fullname" . }}-filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.6.1
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          env:
            - name: ELASTICSEARCH_HOST
              value: {{ include "onestop-dev.fullname" . }}-es-http
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "onestop-dev.fullname" . }}-es-elastic-user
                  key: elastic
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: data
              mountPath: /usr/share/filebeat/data
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: es-certs
              mountPath: /mnt/elastic/tls.crt
              readOnly: true
              subPath: tls.crt
      volumes:
        - name: config
          configMap:
            defaultMode: 0600
            name: {{ include "onestop-dev.fullname" . }}-filebeat
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log
        # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
        - name: data
          hostPath:
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate
        - name: es-certs
          secret:
            secretName: {{ include "onestop-dev.fullname" . }}-es-http-certs-public
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "onestop-dev.fullname" . }}-filebeat
  labels:
    {{- include "onestop-dev.labels.filebeat" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "onestop-dev.fullname" . }}-filebeat
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ include "onestop-dev.fullname" . }}-filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "onestop-dev.fullname" . }}-filebeat
  labels:
    {{- include "onestop-dev.labels.filebeat" . | nindent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "onestop-dev.fullname" . }}-filebeat
  labels:
    {{- include "onestop-dev.labels.filebeat" . | nindent 4 }}
---
{{- end }}
