package org.cedar.onestop.gateway.config;

import com.auth0.jwt.JWT;
import com.auth0.jwt.algorithms.Algorithm;
import org.springframework.http.MediaType;
import org.springframework.security.oauth2.client.endpoint.OAuth2AuthorizationCodeGrantRequest;
import org.springframework.security.oauth2.client.endpoint.WebClientReactiveAuthorizationCodeTokenResponseClient;
import org.springframework.security.oauth2.client.registration.ClientRegistration;
import org.springframework.security.oauth2.core.AuthorizationGrantType;
import org.springframework.security.oauth2.core.ClientAuthenticationMethod;
import org.springframework.security.oauth2.core.endpoint.*;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.io.IOException;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.UnrecoverableEntryException;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.util.Date;
import java.util.UUID;

import static org.springframework.security.oauth2.core.web.reactive.function.OAuth2BodyExtractors.oauth2AccessTokenResponse;

public class WebClientReactivePrivateKeyJwtTokenResponseClient extends WebClientReactiveAuthorizationCodeTokenResponseClient {

  private WebClient webClient;
  private PrivateKeyJwtKeystore privateKeyJwtKeystore;

  public WebClientReactivePrivateKeyJwtTokenResponseClient(WebClient webClient, LoginGovConfiguration loginGovConfiguration) throws NoSuchAlgorithmException, UnrecoverableEntryException, KeyStoreException, IOException {
    this.webClient = webClient;

    LoginGovConfiguration.Keystore keystore = loginGovConfiguration.keystore;

    this.privateKeyJwtKeystore = new PrivateKeyJwtKeystore(
        keystore.file,
        keystore.password,
        keystore.alias,
        null,
        keystore.type
    );
  }

  @Override
  public Mono<OAuth2AccessTokenResponse> getTokenResponse(OAuth2AuthorizationCodeGrantRequest authorizationGrantRequest) {
    return Mono.defer(() -> {
      ClientRegistration clientRegistration = authorizationGrantRequest.getClientRegistration();
      OAuth2AuthorizationExchange authorizationExchange = authorizationGrantRequest.getAuthorizationExchange();
      String tokenUri = clientRegistration.getProviderDetails().getTokenUri();
      BodyInserters.FormInserter<String> body = body(authorizationExchange, clientRegistration, this.privateKeyJwtKeystore);

      // TODO: make the `private_key_jwt` add-ons to the body configurable and optional:
//      clientRegistration.getClientAuthenticationMethod()

      return this.webClient.post()
          .uri(tokenUri)
          .accept(MediaType.APPLICATION_JSON)
          .headers(headers -> {
            if (ClientAuthenticationMethod.BASIC.equals(clientRegistration.getClientAuthenticationMethod())) {
              headers.setBasicAuth(clientRegistration.getClientId(), clientRegistration.getClientSecret());
            }
          })
          .body(body)
          .exchange()
          .flatMap(response -> response.body(oauth2AccessTokenResponse()))
          .map(response -> {
            if (response.getAccessToken().getScopes().isEmpty()) {
              response = OAuth2AccessTokenResponse.withResponse(response)
                  .scopes(authorizationExchange.getAuthorizationRequest().getScopes())
                  .build();
            }
            return response;
          });
    });
  }

  private static Algorithm loginGovSigningAlgorithm(PrivateKeyJwtKeystore privateKeyJwtKeystore) {
    RSAPublicKey publicKey = privateKeyJwtKeystore.rsaPublicKey();
    RSAPrivateKey privateKey = privateKeyJwtKeystore.rsaPrivateKey();
    return Algorithm.RSA256(publicKey, privateKey);
  }

  private static String loginGovJWT(String clientId, String tokenUri, PrivateKeyJwtKeystore keystore) {

    // TODO: make this default to 5 minutes, unless configured otherwise;
    // The expiration time for this token.
    // Should be an integer timestamp (number of seconds since the Unix Epoch)
    // and be a short period of time in the future (such as 5 minutes from now).
    Long expiresIn = LoginGovConstants.LOGIN_GOV_TOKEN_EXPIRATION_TIME;
    Date expiresAt = new Date(System.currentTimeMillis() + expiresIn);

    // The JWT ID, a unique identifier for the token which can be used to prevent reuse of the token.
    // Should be an un-guessable, random string generated by the client.
    String jwtId = UUID.randomUUID().toString();

    // this client's private key for
    Algorithm signingAlgorithm = loginGovSigningAlgorithm(keystore);

    // This JWT represents the `client_assertion` in login.gov's token request.
    // https://developers.login.gov/oidc/#token
    return jwt(clientId, clientId, tokenUri, jwtId, expiresAt, signingAlgorithm);
  }

  private static String jwt(String subject, String issuer, String audience, String jwtId, Date expiresAt, Algorithm signingAlgorithm) {
    return JWT.create()
        .withSubject(subject)
        .withIssuer(issuer)
        .withAudience(audience)
        .withJWTId(jwtId)
        .withExpiresAt(expiresAt)
        .sign(signingAlgorithm);
  }

  private static BodyInserters.FormInserter<String> body(OAuth2AuthorizationExchange authorizationExchange, ClientRegistration clientRegistration, PrivateKeyJwtKeystore privateKeyJwtKeystore) {
    OAuth2AuthorizationResponse authorizationResponse = authorizationExchange.getAuthorizationResponse();
    BodyInserters.FormInserter<String> body = BodyInserters
        .fromFormData(OAuth2ParameterNames.GRANT_TYPE, AuthorizationGrantType.AUTHORIZATION_CODE.getValue())
        .with(OAuth2ParameterNames.CODE, authorizationResponse.getCode());
    String redirectUri = authorizationExchange.getAuthorizationRequest().getRedirectUri();
    String codeVerifier = authorizationExchange.getAuthorizationRequest().getAttribute(PkceParameterNames.CODE_VERIFIER);
    if (redirectUri != null) {
      body.with(OAuth2ParameterNames.REDIRECT_URI, redirectUri);
    }
    if (!ClientAuthenticationMethod.BASIC.equals(clientRegistration.getClientAuthenticationMethod())) {
      body.with(OAuth2ParameterNames.CLIENT_ID, clientRegistration.getClientId());
    }
    if (ClientAuthenticationMethod.POST.equals(clientRegistration.getClientAuthenticationMethod())) {
      body.with(OAuth2ParameterNames.CLIENT_SECRET, clientRegistration.getClientSecret());
    }
    if (codeVerifier != null) {
      body.with(PkceParameterNames.CODE_VERIFIER, codeVerifier);
    }

    String jwt = loginGovJWT(
        clientRegistration.getClientId(),
        clientRegistration.getProviderDetails().getTokenUri(),
        privateKeyJwtKeystore
    );

    body.with("client_assertion", jwt);
    body.with("client_assertion_type", LoginGovConstants.LOGIN_GOV_CLIENT_ASSERTION_TYPE);

    return body;
  }
}
