# Default values for kibana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana
  tag: 5.5.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5601
  # containerPort: 5601

elasticsearch:
  name: "elasticsearch"
  port: 9200
  enabled: false  # set to false to use external elasticsearch
  # serviceNameOverride:  # used to point to external elasticsearch service

ingress:
  enabled: true
  annotations: {}
  paths:
  - "/kibana"
  hosts:
  - "localhost"
  tls: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
