{{- if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onestop-search.configname" . }}
  labels: {{- include "onestop-search.labels" . | nindent 4 }}
data:
  application.yml: {{ .Values.config | toYaml | indent 4 }}
  {{- end }}
