--
-- insert into savesearch (id, name, user_id, value)
--  values ('1', 'User Name 1', 'UserId1', 'http://acf3425c8d');
--
-- insert into savesearch (id, name, user_id, value)
--  values ('2', 'User Name 2', 'UserId2', 'http://acf3425c8d');
--
-- insert into savesearch (id, name, user_id, value)
--  values ('3', 'User Name 3', 'UserId3', 'http://acf3425c8d');
--
-- insert into savesearch (id, name, user_id, value)
--  values ('4', 'User Name 4', 'UserId4', 'http://acf3425c8d');
--
-- INSERT INTO onestop_users (user_id) VALUES ('deez');
--
-- INSERT INTO onestop_roles (role_id, name) VALUES ('nuts', 'PUBLIC');
--
-- INSERT INTO onestop_users_roles (user_id, role_id) VALUES ('deez', 'nuts')
-- -- INSERT INTO onestop_roles (name) VALUES ('ADMIN');