apiVersion: v1
description: A Helm chart for the OneStop system
name: onestop
version: "3.0.0-alpha"

dependencies:
  - name: cp-helm-charts
    version: ~0.1.0
    repository: https://confluentinc.github.io/cp-helm-charts/
    condition: cp.enabled,global.cp.enabled
  - name: elasticsearch
    version: ~0.1.0
    repository: file://../elasticsearch
    condition: elasticsearch.enabled,global.elasticsearch.enabled
  - name: onestop-client
    version: ~0.1.0
    repository: file://../onestop-client
    conditions: onestop-client.enabled,global.onestop-client.enabled
  - name: onestop-parsalyzer
    version: ~0.4.0
    repository: file://../onestop-parsalyzer
    conditions: parsalyzer.enabled,global.parsalyzer.enabled
  - name: onestop-registry
    version: ~0.4.0
    repository: file://../onestop-registry
    conditions: registry.enabled,global.registry.enabled
  - name: onestop-search
    version: ~0.1.0
    repository: file://../onestop-search
    conditions: onestop-search.enabled,global.onestop-search.enabled
  # - name: onestop-user
  #   version: ~0.1.0
  #   repository: file://../onestop-user
  #   conditions: onestop-user.enabled,global.onestop-user.enabled
