---
apiVersion: v1
kind: Service
metadata:
  name: onestop-api-metadata
  labels:
    environment: dev
    tier: "backend"
    devmode: "true"
spec:
  selector:
    app: onestop-api-metadata
  ports:
    - name: http
      port: 8098
      targetPort: 8098
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onestop-api-metadata
  labels:
    tier: "backend"
    devmode: "true"
spec:
  selector:
    matchLabels:
      app: onestop-api-metadata
  template:
    metadata:
      labels:
        app: onestop-api-metadata
    spec:
      containers:
      - name: onestop-api-metadata
        image: cedardevs/onestop-api-metadata:latest
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: LOGGING_LEVEL_ORG.CEDAR.ONESTOP.API
          value: DEBUG
        ports:
        - containerPort: 8098
      restartPolicy: Always
