---
apiVersion: v1
kind: Service
metadata:
  name: onestop-logstash
  labels:
    environment: dev
    tier: "backend"
    devmode: "true"
spec:
  selector:
    app: onestop-logstash
  ports:
    - name: http
      port: 5044
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onestop-logstash
  labels:
    tier: "backend"
    devmod: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onestop-logstash
  template:
    metadata:
      labels:
        app: onestop-logstash
    spec:
      restartPolicy: Always
      containers:
      - name: onestop-logstash
        image: cedardevs/onestop-logstash
        env:
        ports:
        - containerPort: 5044
          name: http