apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-admin.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "api-admin.name" . }}
    helm.sh/chart: {{ include "api-admin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "api-admin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.config }}
      annotations:
        checksum/config: {{ . | sha256sum }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "api-admin.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          # EXPORT ADDITIONAL CONFIG LOCATION (if config provided)
          {{- if .Values.config }}
            # if Helm values have a config section, it will be mounted as a YML file
            # this tells Spring where the additional config file is mounted
            - name: SPRING_CONFIG_ADDITIONAL-LOCATION
              value: /etc/conf/application.yml
          {{- end }}
          # EXPORT ACTIVE SPRING PROFILES TO TELL SPRING WHICH FEATURES TO ENABLE
          # the loop is making a comma delimited list for multi-feature handling
            - name: SPRING_PROFILES_ACTIVE
              value: '{{ $active := dict "profiles" (list) -}}
                      {{- range $feature, $enabled := .Values.features -}}
                        {{- if $enabled -}}
                          {{- $noop := $feature | append $active.profiles | set $active "profiles" -}}
                        {{- end -}}
                      {{- end -}}
                      {{- join "," $active.profiles }}'
          # EXPORT PATHS TO KEYSTORES (if icam feature enabled)
          {{- if .Values.features.icam }}
            - name: ICAM_KEYSTORE_FILE
              value: {{ .Values.keystoreFiles.jks.icam }}
          {{- end }}
          # generic env overrides, for spring properities, etc
          {{- if .Values.env }}
            {{- range $envName,$envVal := .Values.env }}
            - name: {{ $envName }}
              value: {{ $envVal | quote }}
            {{- end }}
          {{- end }}
          # EXPORT SECRET ENVIRONMENT VARIABLES IN THIS CONTAINER (if icam feature enabled)
          # the general utility here is taking "env" type secrets in our Helm values,
          # mapping the keys directly to environment variables w/optional prefix,
          # and uppercasing / replacing problematic '-' and '.' characters with '_'
          {{- if .Values.features.icam }}
            {{- range $secret := .Values.secrets }}
              {{- if eq $secret.type "env" }}
                {{- range $key := $secret.keys }}
                  {{- $envPrefix := $secret.prefix | default "" | upper }}
                  {{- $envKey := $key | upper | replace "." "_" | replace "-" "_" }}
            - name: {{ $envPrefix }}{{ $envKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret.name }}
                  key: {{ $key }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
          # This liveness probe is necessary on both API deployments because they now trigger a runtime exception when
          # they cannot gather the Elasticsearch version information from a running Elasticsearch service.
          #
          # Tomcat will try to deploy the WAR initially, but the underlying Spring app can die for the reason mentioned
          # above, without trying to restart. This is because the base container only cares that Tomcat is running and
          # not necessarily the WAR app itself.
          #
          # The initial delay here allows Tomcat time to deploy the WAR. The fact that an endpoint comes back also
          # guarantees that a running Elasticsearch version was gathered upon Spring startup.
          livenessProbe:
            httpGet:
              port: http
              path: /onestop-admin/actuator/info
            initialDelaySeconds: 60 # wait n seconds before initiating the probe
            periodSeconds: 20       # how often this probe should be run
            timeoutSeconds: 10      # how long to wait before timing out the probe
            failureThreshold: 1     # try n times before restarting the pod
            successThreshold: 1     # min # of consecutive successes for probe to be successful after having failed
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          # MOUNT ADDITIONAL CONFIG IN THIS CONTAINER (if config provided)
          # done via ConfigMap and associated volume
          {{- if .Values.config }}
            - name: config-volume
              mountPath: /etc/conf/
          {{- end }}
          # MOUNT SECRET FILES IN THIS CONTAINER (if icam feature enabled)
          # if there are multiple containers in the pod,
          # then each container needs its own volumeMounts block
          {{- if .Values.features.icam }}
            {{- range $secret := .Values.secrets }}
              {{- if eq $secret.type "file" }}
            - name: {{ $secret.name }}-volume
              mountPath: {{ $secret.path }}
              readOnly: true
              {{- end }}
            {{- end }}
          {{- end }}
      volumes:
      # CREATE VOLUME FOR ADDITIONAL CONFIG (if config provided)
      # additional location for Spring config allows overriding defaults
      {{- if .Values.config }}
        - name: config-volume
          configMap:
            name: {{ include "api-admin.configname" . }}
      {{- end }}
      # CREATE VOLUME FOR SECRET FILES (if icam feature enabled)
      # secret must be created in the Kubernetes API before it can be used
      # only 1 `spec.volumes` entry is needed per secret, even if it contains multiple keys
      {{- if .Values.features.icam }}
        {{- range $secret := .Values.secrets }}
          {{- if eq $secret.type "file" }}
        - name: {{ $secret.name }}-volume
          secret:
            secretName: {{ $secret.name }}
          {{- end }}
        {{- end }}
      {{- end }}
#      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
