---
spring:
  security:
    oauth2:
      client:
        registration:
          login-gov:
            client-id: \${LOGIN_GOV_CLIENT_ID}
            #client-secret: logingovsecret
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: openid, email
        provider:
          login-gov:
            authorization-uri: https://idp.int.identitysandbox.gov/openid_connect/authorize
            token-uri: https://idp.int.identitysandbox.gov/api/openid_connect/token
            user-info-uri: https://idp.int.identitysandbox.gov/api/openid_connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://idp.int.identitysandbox.gov/api/openid_connect/certs

login-gov:
  allowed-origin: \${LOGIN_GOV_ALLOWED_ORIGIN}
  login-success-redirect: \${LOGIN_GOV_LOGIN_SUCCESS_REDIRECT}
  login-failure-redirect: \${LOGIN_GOV_LOGIN_FAILURE_REDIRECT}
  logout-success-redirect: \${LOGIN_GOV_LOGOUT_SUCCESS_REDIRECT}
  keystore:
    alias: \${LOGIN_GOV_KEYSTORE_ALIAS}
    file: \${LOGIN_GOV_KEYSTORE_FILE}
    password: \${LOGIN_GOV_KEYSTORE_PASSWORD}
    #keyPassword: \${LOGIN_GOV_KEY_PASSWORD}
    type: JKS

# this section allows the client login features to activate
ui:
  auth:
    loginEndpoint: \${UI_AUTH_LOGIN_ENDPOINT}
    logoutEndpoint: \${UI_AUTH_LOGOUT_ENDPOINT}
    userProfileEndpoint: \${UI_AUTH_USER_PROFILE_ENDPOINT}