{{ if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "onestop-registry.fullname" . }}-config
  labels: {{- include "onestop-registry.labels" . | nindent 4 }}
data:
  application.yaml: {{ .Values.config | toYaml | nindent 4 }}
{{- end }}
