---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onestop-registry.fullname" . }}-headless
  labels: {{- include "onestop-registry.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
  - port: 9090
    targetPort: db
    name: db
  selector:
    app: {{ include "onestop-registry.name" . }}
    release: {{ .Release.Name }}
