---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onestop-registry.fullname" . }}
  labels: {{- include "onestop-registry.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "onestop-registry.selectorLabels" . | nindent 4 }}
