FROM nginx:alpine

# Update
RUN apk add --update nodejs
EXPOSE 80
VOLUME /opt/nginx/html
# Run npm install -gradle
# Run npm build -gradle
# Mount built product folder to nginx served content


# COPY wrapper.sh /
#
# COPY dist /usr/share/nginx/html
#
# CMD ["./wrapper.sh"]
