# Tasks to install and start the onestop api application
---

- name: Ensure the latest java is installed
  become: true
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: latest

- name: Create a onestop group
  become: true
  group:
    name: onestop
    state: present

- name: Create a onestop user
  become: true
  user:
    name: onestop
    group: onestop
    state: present

- name: Create the installation directory
  become: true
  file:
    path: "{{ install_base }}"
    owner: onestop
    group: onestop
    state: directory

- name: Download tomcat
  become: true
  get_url:
    url: "{{ tomcat_url }}"
    checksum: "{{ tomcat_checksum }}"
    dest: "{{ install_base }}"
    owner: onestop
    group: onestop
  register: tomcat_download

- name: Install tomcat
  become: true
  unarchive:
    remote_src: yes
    src: "{{ tomcat_download.dest }}"
    dest: "{{ install_base }}"
    owner: onestop
    group: onestop
  register: tomcat_install

- name: Download latest api snapshot
  become: true
  maven_artifact:
    repository_url: https://oss.jfrog.org/oss-snapshot-local
    group_id: cires.ncei.onestop
    artifact_id: onestop-api
    version: latest
    extension: war
    dest: "{{ tomcat_base }}/webapps/onestop-api.war"
    state: present
  register: api_download

- name: Set the permissions on the api app
  become: true
  file:
    path: "{{ api_download.dest }}"
    owner: onestop
    group: onestop
    mode: 440

- name: Install the api conf file
  become: true
  template:
    src: templates/onestop-api.yml
    dest: "{{ config_path }}"
    owner: onestop
    group: onestop
    mode: 440
  register: conf

- name: Stop the api service if something changed
  become: true
  systemd:
    name: onestop-api
    state: stopped
  when: tomcat_download.changed or api_download.changed or conf.changed

#- name: Stop the api service if something changed
#  become: true
#  service:
#    name: onestop-api
#    state: stopped
#  when: tomcat_download.changed or api_download.changed or conf.changed

- name: Install the api as a systemd service
  become: true
  template:
    src: templates/onestop-api.service
    dest: /etc/systemd/system/onestop-api.service
    owner: root
    group: root
    mode: 664

- name: Start the api as a systemd service
  become: true
  systemd:
    name: onestop-api
    daemon_reload: yes
    state: "{{ 'restarted' if tomcat_download.changed or api_download.changed or conf.changed else 'started'}}"
    enabled: true

#- name: Start the api as a system service
#  become: true
#  service:
#    name: onestop-api
#    state: "{{ 'restarted' if tomcat_download.changed or api_download.changed or conf.changed else 'started'}}"
#    enabled: true
